#!/bin/sh

set -e

mkdir -p ~/.config/shaur && cd ~/.config/shaur

checkNet () (
	ping -c1 -W 2 google.com >& /dev/null || exit
)

dbupdate () (
	echo "[AUR database update]"
	curl -s --url 'https://aur.archlinux.org/packages.gz' --create-dirs --output "packages.gz" >/dev/null && gunzip -f "packages.gz"
	sort -o packages packages
)

key () (
	key=$(grep '^validpgpkeys' < PKGBUILD | cut -d"(" -f2  | cut -d")" -f1 | tr -d "'")
	if [ "$key" ]; then gpg --recv-keys "$key"; fi
)

downloadPackage () (
	version=$(pacman -Qm | grep -i "$1" | awk '{print $2}')
	git clone "https://aur.archlinux.org/$1.git" >/dev/null
)

installPackage () (
	cd "$1" && (key; makepkg -si)
)

upgradePackage () (
	cd "$1" && (sudo pacman -U -- *.zst || (cd .. && installPackage "$1"))
)

downgrade () (
	op=$(echo "$1" | cut -d " " -f2-)

        if [ "$1" = "$op" ]; then
		ls -d */ > packInCache
		name=$(sk -m --bind change:top --layout=reverse < packInCache)
	else
		name="$op"
	fi
	for i in $name; do
		echo "$i"	
		installPackage "$i"
#		cd ..
	done
)

upgrade () (
	loadscreen=0
	load[0]="loading... [----------]"
	load[1]="loading... [#---------]"
	load[2]="loading... [##--------]"
	load[3]="loading... [###-------]"
	load[4]="loading... [####------]"
	load[5]="loading... [#####-----]"
	load[6]="loading... [######----]"
	load[7]="loading... [#######---]"
	load[8]="loading... [########--]"
	load[9]="loading... [#########-]"
	load[10]="loading... [##########]"
	dbupdate
	
	pacman -Qm > AurInstalled
	sort -o AurInstalled AurInstalled
	numPack=$(cat "AurInstalled" | wc -l)
	doLoad=$(( 100 / $numPack + 1 ))
	nextLoad=0;
	while read -r x; do
		nextLoad=$nextLoad+$doLoad	
		loaded=$(( nextLoad / 10 ))
		echo -ne "\e[96m${load[$loaded]} $(( $nextLoad - $doLoad))% \033[0K\r" #${load[$doLoad]}
		name=$(echo "$x" | awk '{print $1}')
		version=$(echo "$x" | awk '{print $2}')
		vRemote=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=search&by=name&arg=$name" | jq '.results[]' | jq "select(.Name==\"$name\")" | jq -r '.Version')
		
		if [ "$(vercmp "${version}" "${vRemote}")" -lt 0 ]; then
			echo "[$name] $version to -> $vRemote"
			
			PackageBase=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=search&by=name&arg=$name" | jq '.results[]' | jq "select(.Name==\"$name\")" | jq -r '.PackageBase')

			if [ "$PackageBase" ]; then
				if [ -d "$PackageBase" ]; then
					rm -rf "$PackageBase"
				fi
				downloadPackage "$PackageBase" && installPackage "$PackageBase"
				version=$(pacman -Qm | grep -i "$PackageBase" | awk '{print $2}')
				mv "$PackageBase" "$PackageBase-$version"
			else
				echo "ERROR 404: $x NOT FOUND..."
			fi
		fi
	done < AurInstalled
	echo -ne "FULL [##########] 100"
)

sync () (
	! [ -f packages ] && echo "DB not found, type: shaur -y" && exit
	
	op=$(echo "$1" | cut -d " " -f2-)

	if [ "$1" = "$op" ]; then
		name=$(sk -m --bind change:top --layout=reverse --preview "curl -s \"https://aur.archlinux.org/rpc/?v=5&type=search&by=name&arg=\"{}\"\" | jq '.results[]' > tmp && jq 'select(.Name==\"{}\")' < tmp" < packages)
	else
		name="$op"
	fi
	for i in $name; do	
		pacman -Qqm > AurInstalled
		sort -o AurInstalled AurInstalled
		PackageBase=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=search&by=name&arg=$i" | jq '.results[]' | jq "select(.Name==\"$i\")" | jq -r '.PackageBase')
		
		if [ "$PackageBase" ]; then
			if [ -d "$PackageBase" ]; then
				rm -rf "$PackageBase"
			fi
			if [ $(cat AurInstalled | grep -i $PackageBase) ]; then
				echo "package already installed. do you want to reinstall it? [y/N]: "
				read -r rep
	
				case $rep in
				([y]|[Y]|"")
					version=$(pacman -Qm | grep -i "$PackageBase" | awk '{print $2}')
					downloadPackage "$PackageBase" && installPackage "$PackageBase"
					if [ -d "$PackageBase-$version" ]; then
						rm -rf "$PackageBase-$version"
					fi
					mv "$PackageBase" "$PackageBase-$version"
				;;
				(*) ;;
				esac
			else
				downloadPackage "$PackageBase" && installPackage "$PackageBase"
				version=$(pacman -Qm | grep -i "$PackageBase" | awk '{print $2}')
				mv "$PackageBase" "$PackageBase-$version" 
			fi
		else
			echo "ERROR 404: $x NOT FOUND..."
		fi
	done
)

remove () {
	pacman -Qqm > AurInstalled
	sort -o AurInstalled AurInstalled

	op=$(echo "$2" | cut -d " " -f2-)

	if [ "$1" = "$op" ]; then
		name=$(sk -m --bind change:top --layout=reverse --preview "curl -s \"https://aur.archlinux.org/rpc/?v=5&type=search&by=name&arg=\"{}\"\" | jq '.results[]' > tmp && jq 'select(.Name==\"{}\")' < tmp" < AurInstalled )
	else
		name="$op"
	fi
		
	# improve
	for i in $name; do sudo pacman --noconfirm "$1" "$i"; done
}

removeCache () {
	echo "Cache directory: ~/.config/shaur"
	printf "do you want to remove ALL cached packages? [y/N]: "
	read -r rep

	case $rep in
		([y]|[Y]|"") rm -rf -- */ ;;
		(*) echo "Interrupting" ;;
	esac
}

query () (
	pacman -Qqm > AurInstalled
	sort -o AurInstalled AurInstalled

	op=$(echo "$1" | cut -d " " -f2-)

	if [ "$1" = "$op" ]; then
		name=$(sk -m --bind change:top --layout=reverse --preview "curl -s \"https://aur.archlinux.org/rpc/?v=5&type=search&by=name&arg=\"{}\"\" | jq '.results[]' > tmp && jq 'select(.Name==\"{}\")' < tmp" < AurInstalled )
	else
		name="$op"
	fi

	for i in $name; do
		curl -s "https://aur.archlinux.org/rpc/?v=5&type=search&by=name&arg=$i" | jq '.results[]' | jq "select(.Name==\"$i\")" > tmp
		cat ./tmp
	done
)

version () (
	echo "shaur version: alpha"
)

getHelp() (
	echo "Usage:
	shaur <operation> (you can use only one option) 

Operations:
	-h --help
	-U --upgrade 		
	-S --sync
	-R --remove
	-C --removeCache
	-Q --query
	-V --version
	-y --dbupdate"
)

[ ! "$*" ] && getHelp && exit

case $1 in
	-y | --dbupdate) checkNet && dbupdate ;;
	-U | --upgrade) checkNet && upgrade ;;
	-D | --downgrade) downgrade "$*" ;;
	-S | --sync) checkNet && sync "$*" ;;
	-R*| --remove) remove "$1" "$*" ;;
	-C | --removeCache ) removeCache ;;
	-Q | --query ) query "$*" ;;
	-V | --version ) version ;;
	-h | --help) getHelp ;;
	*)
		echo "shaur -> invalid option $*"
		echo "Try shaur -h or --help for more information"
	;;
esac
